name: tests-tickets

on:
  pull_request:
    paths:
      # trigger testing only from changes made to this service
      - 'tickets/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
