name: tests-orders

on:
  pull_request:
    paths:
      # trigger testing only from changes made to this service
      - 'orders/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
